# Site settings
title: Ponaehal
email: mail@viorel-roman.org
description: "Blogul unui emigrant moldovean in Rusia"
baseurl: ""
url: "http://gnunixon.github.io"
twitter_username: gnunixon
github_username:  gnunixon

# Build settings
markdown: kramdown
permalink: pretty
